### ISSUE TITLE
Add new timezones to list

### ISSUE THREAD

**Issue by mvrhov** [mweber26/timestampandtz#3]
Skipping the posix prefixed timezones pg_timezone_name in PG 10 shows 607 rows.

**Comment by mweber26** [comment]
I'll have to try to remember how to update the timezone ids.  I've only  done in that first time.

**Comment by mweber26** [comment]
My pg10 (and pg11b1) show 592 with the following missing:

name | abbrev | utc_offset | is_dst
----------------------|--------|------------|--------
 Pacific/Bougainville | +11    | 11:00:00   | f
 America/Punta_Arenas | -03    | -03:00:00  | f
 America/Fort_Nelson  | MST    | -07:00:00  | f
 Asia/Atyrau          | +05    | 05:00:00   | f
 Asia/Tomsk           | +07    | 07:00:00   | f
 Asia/Chita           | +09    | 09:00:00   | f
 Asia/Barnaul         | +07    | 07:00:00   | f
 Asia/Yangon          | +0630  | 06:30:00   | f
 Asia/Srednekolymsk   | +11    | 11:00:00   | f
 Asia/Famagusta       | EEST   | 03:00:00   | t
 Europe/Ulyanovsk     | +04    | 04:00:00   | f
 Europe/Saratov       | +04    | 04:00:00   | f
 Europe/Kirov         | +03    | 03:00:00   | f
 Europe/Astrakhan     | +04    | 04:00:00   | f
 posixrules           | EDT    | -04:00:00  | t
(15 rows)
