### ISSUE TITLE
Compilation under postgresql 10 fails

### ISSUE THREAD

**Issue by mvrhov** [mweber26/timestampandtz#5]

**Comment by kchsherbakov** [comment]
Hi, @mvrhov!
I've recently faced up the same problem. Could you please tell me, what is your target platform? Linux-based or Windows? 
I've tried to build it on Windows 10 (latest update for now) but without success. Is it platform-specific issue or is it PostgreSQL's bug?

**Comment by mvrhov** [comment]
It's not platform specific. Postgresql 10 changed some headers, so some definitions are different.

**Comment by mweber26** [comment]
I will look into it.

**Comment by mvrhov** [comment]
Ooooo. 👍 💯
