### ISSUE TITLE
Timezones without / not working

### ISSUE THREAD

**Issue by mvrhov** [mweber26/timestampandtz#6]
I don't know what's going on, but it seems that when compiled (ubuntu 16.04 gcc 5.4 ) some of the timezones that don't have / in name are not working. e.g NZ, UTC, PRC,...
however some of them like  GTM, Japan do work
The most problematic one of corse being UTC.

`
SET time zone 'UTC';
SELECT '2018-12-01 00:00:00'::timestampandtz

ERROR: missing timezone ID "UTC" while parsing timestampandtz "2018-12-01 00:00:00" LINE 1: SELECT '2018-12-01 00:00:00'::timestampandtz
`

**Comment by mvrhov** [comment]
If I'm not crazy you are bisecting the timezones, when searching for a correct one.
Well this means that the timezones struct is supposed to be sorted :)

**Comment by mweber26** [comment]
You are right.  Check out b289fd9, it should work now.

**Comment by mweber26** [comment]
We also need the zones by ID.  d66cb66 should fix that.

**Comment by mvrhov** [comment]
Thanks
